weapons ={  'Glove':'グローブ',
            'Tonfa':'トンファー',
            'Bat':'バット',
            'Whip':'鞭',
            'HighAngleFire':'投げ',
            'DirectFire':'暗器',
            'Bow':'弓',
            'CrossBow':'石弓',
            'Pistol':'拳銃',
            'AssaultRifle':'突撃小銃',
            'SniperRifle':'狙撃銃',
            'Camera':'カメラ',
            'Hammer':'金槌',
            'Axe':'斧',
            'OneHandSword':'短剣',
            'TwoHandSword':'両手剣',
            'DualSword':'双剣',
            'Spear':'槍',
            'Nunchaku':'双節棍',
            'Rapier':'レイピア',
            'Guitar':'ギター',
            'VFArm':'VF義手',
            'Arcana':'アルカナ'
            }
weapons_file ={  
            'Glove':'glove',
            'Tonfa':'tonfa',
            'Bat':'bat',
            'Whip':'whip',
            'HighAngleFire':'throw',
            'DirectFire':'shuriken',
            'Bow':'bow',
            'CrossBow':'crossbow',
            'Pistol':'pistol',
            'AssaultRifle':'ar',
            'SniperRifle':'sr',
            'Camera':'camera',
            'Hammer':'hammer',
            'Axe':'axe',
            'OneHandSword':'dagger',
            'TwoHandSword':'twohandedsword',
            'DualSword':'dualswords',
            'Spear':'spear',
            'Nunchaku':'nunchaku',
            'Rapier':'rapier',
            'Guitar':'guitar',
            'VFArm':'vfp'
}
characters = {  'Jackie':'ジャッキー',
                'Aya':'アヤ',
                'Fiora':'フィオラ',
                'Hyunwoo':'ヒョヌ',
                'Magnus':'マグヌス',
                'Zahir':'ザヒル',
                'Nadine':'ナディン',
                'Hart':'ハート',
                'Isol':'アイソル',
                'LiDailin':'ダイリン',
                'Yuki':'雪',
                'Hyejin':'ヘジン',
                'Xiukai':'シウカイ',
                'Chiara':'キアラ',
                'Sissela':'シセラ',
                'Silvia':'シルヴィア',
                'Adriana':'アドリアナ',
                'Shoichi':'彰一',
                'Emma':'エマ',
                'Lenox':'レノックス',
                'Rozzi':'ロッジ',
                'Luke':'ルク',
                'Cathy':'キャッシー',
                'Adela':'アデラ',
                'Bernice':'バニス',
                'Barbara':'バーバラ',
                'Alex':'アレックス',
                'Sua':'スア',
                'Leon':'レオン',
                'Eleven':'Eleven',
                'Rio':'莉央',
                'William':'ウィリアム',
                'Nicky':'ニッキー',
                'Nathapon':'ナタポン',
                'Jan':'ヤン',
                'Eva':'エヴァ',
                'Daniel':'ダニエル',
                'Jenny':'ジェニー',
                'Camilo':'カミロ',
                'Chloe':'クロエ',
                'Johann':'ヨハン',
                'Bianca':'ビアンカ',
                'Celine':'セリーヌ',
                'Echion':'エキオン',
                'Mai':'マイ',
                'Aiden':'エイデン',
                'Laura':'ラウラ',
                'Tia':'ティア',
                'Felix':'フェリックス',
                'Elena':'エレナ',
                'Priya':'プリヤ',
                'Adina':'アディナ',
                'Markus':'マーカス',
                'Karla':'カーラ',
                'Estelle':'エステル',
                'Piolo':'ピオロ',
                'Martina':'マルティナ',
                'Haze':'ヘイズ',
                'Isaac':'アイザック',
                'Tazia':'タジア',
                'Irem':'イレム',
                'Theodore':'テオドール',
                'Lyanh':'イアン',
                'Vanya':'ヴァーニャ',
                'DebiMarlene':'デビー&マーリン',
                'Arda':'アルダ',
                'Abigail':'アビゲイル',
                'Alonso':'アロンソ',
                'Leni':'レニ',
                'Tsubame':'つばめ',
                'Kenneth':'ケネス',
                'Katja':'カティア',
                'Charlotte':'シャーロット',
                'Darko':'ダルコ',
                'Lenore':'レノア',
                'Garnet':'ガーネット'
                               
}
defaultcols = [ 'rank',
                'level',
                'character',
                'nickname',
                'weapon',
                'best weapon mastery',
                'best weapon mastery level',
                'total field kill',
                'team kill',
                'kill',
                'assist',
                'hunting',
                'killer',
                'gameId',
                'teamName',
                'aug',
                'augsub']
def_characterstatistics= [  'comp',
                            'character',
                            'weapon',
                            'picked',
                            'winper',
                            'kill',
                            'fieldkill',
                            'avgkill',
                            'avgrank' ]

def_playerstatistics= [ 'name',
                        'character',
                        'played',
                        'winper',
                        'kill',
                        'avgkill',
                        'avgrank' ]

def_teamstatistics = [  'name',
                        'played',
                        'winper',
                        'kill',
                        'avgkill',
                        'avgrank']
                        
solo_matrix = { '1' :32,
                '2' :16,
                '3' :8,
                '4' :4,
                '5' :2,
                '6' :1,
                '7' :0,
                '8' :0,
                '9' :0,
                '10':0,
                '11':0,
                '12':0,
                '13':0,
                '14':0,
                '15':0,
                '16':0,
                '17':0,
                '18':0,}
duo_matrix = {  '1' :32,
                '2' :16,
                '3' :8,
                '4' :4,
                '5' :2,
                '6' :1,
                '7' :0,
                '8' :0,
                '9' :0}

sqd_matrix = {  '1' :8,
                '2' :5,
                '3' :4,
                '4' :3,
                '5' :2,
                '6' :1,
                '7' :0,
                '8' :0}

kill_matrix = [1,1,1]
